//board
let blockSize =25;
let rows =20;
let cols =20;
let board;
let context; //this the drawing object to be drawn on the board

let GameOver =false;


//food
let foodX;
let foodY;
//snake Head
let snakeX = blockSize * 5;
let snakeY = blockSize * 5 ; 
//the above snakeX and snakeY  position the start of the snake at  (5,5);


  //this give the snake speed to move
  velocityX = 0;
  velocityY = 0;

  //snake body in the Array form which increases in size
  //the body array is to store a banch of segiments
 let snakeBody =[];

window.onload =function(){
    board =document.getElementById('board');
    board.height =rows * blockSize; //this is the height of the board
    board.width = cols * blockSize; //thos gives the width of the board
    context =board.getContext("2d"); //this is used to Draw on the board
    document.addEventListener('keyup',chamgeDirection); //note the event case writting
    placeFood();
    setInterval(Update , 200);
    // Update(); //this function is to re-draw the board on the screen
}

function Update(){

if(GameOver){
    return;
}


    //this is the board
context.fillStyle ="black";
context.fillRect(0,0,board.width,board.height);

//this is the food
context.fillStyle ="red";
context.fillRect(foodX,foodY, blockSize ,blockSize);

//this is the what happens if the snake eats the food
if(snakeX == foodX && snakeY == foodY){
    //the above condition means the food and the snake are in the same square

    //here are is wat happens to the array body snake
    snakeBody.push([foodX,foodY]);
        placeFood();
}

//this is to move the new body array add together with the head
for (let i =snakeBody.length -1; i > 0; i--) {
    //here the movement is starting from the end of the snake to the head of snake
    snakeBody[i] = snakeBody[i -1];
}
//below code is to update the second segment to take the head's place
if(snakeBody.length)//if there are body parts then do the follow condition code
{
    snakeBody[0]    = [snakeX ,snakeY];
    //before the haed set to head
}

//this is the snake it self in the new placess
context.fillStyle ="lime";
snakeX += velocityX * blockSize;
snakeY += velocityY * blockSize;
context.fillRect(snakeX,snakeY ,blockSize ,blockSize);// blocksize ,blocksize in this line are of the same size in width & height

    //here is to draw the new array body on the board
    for(let i=0; i<snakeBody.length; i++){
    context.fillRect(snakeBody[i][0],snakeBody[i][1],blockSize, blockSize);
    }

    //here are the condition for game over
    // codition one  when the snake is out of boundary
    if(snakeX < 0 || snakeX > cols*blockSize || snakeY < 0 || snakeY > rows*blockSize){
        GameOver =true;
        alert('GameOver Snake Out of Boudary');
        
    }
    //condition two when the  snake eats its self 
   for (let i = 0; i < snakeBody.length; i++) //this for loop determines the length of the snake body
   {
        if(snakeX ==snakeBody[i][0] && snakeY ==snakeBody[i][1])//this determine the colusion point of the snake its self
        {
            GameOver =true;
            alert('GameOver Snake Eats its Self');
        }
   }
}  


//function of the random food placer
function placeFood(){
    foodX= Math.floor(Math.random() * cols) * blockSize;
    foodY =Math.floor(Math.random() * rows) *blockSize;
}
function chamgeDirection(e){
    //the e.code rep thephysical key on the keyboard(as opposide to  the character generated by pressing the Key) s
    //keyboardEvents.code
    if(e.code == 'ArrowUp' && velocityY != 1){
        //here u are moving in the upward direction
        velocityX = 0;
        velocityY= -1;
    }
    else if(e.code == 'ArrowDown' && velocityY != -1){ 
        //here u are moving in the Downward direction
        velocityX = 0;
        velocityY= 1;
    }
    else if(e.code == 'ArrowLeft' && velocityX != 1){
        //here u are moving in the LeftWard direction
        velocityX = -1;
        velocityY= 0;
    }
    else if(e.code == 'ArrowRight' && velocityX != -1){
        //here u are moving in the Rightward direction
        velocityX = 1;
        velocityY= 0;
    }
}
